-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 11:10:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webcrafters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webcrafters` DEFAULT CHARACTER SET utf8 ;
USE `webcrafters` ;

-- -----------------------------------------------------
-- Table `webcrafters`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webcrafters`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `webcrafters`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webcrafters`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuarios` INT NOT NULL,
  `data` DATE NULL,
  `comentario` TEXT(1000) NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuarios_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `webcrafters`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `webcrafters`.`usuarios` (nome, sobrenome, email, telefone, senha, ativo) VALUES
 ('Admin', 'do Sistema', 'admin@localhost', '00000000000', '12345', 1),
 ('Alessandro', 'Nascimento', 'arn_nascimento@hotmail.com', '61985951355', '12345', 1);